# Generated by Django 2.2.7 on 2019-12-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalhistory',
            name='brush',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentalhistory',
            name='floss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentalhistory',
            name='rinse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
