# Generated by Django 2.2.7 on 2019-12-21 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('track_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackrecord',
            name='clinical_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ClinicalInstructor'),
        ),
    ]
