# Generated by Django 2.2.7 on 2019-12-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalhistory',
            name='bled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalhistory',
            name='relevant_bled',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
