# Generated by Django 2.2.7 on 2019-12-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0002_auto_20191216_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='occlusion',
            name='generalized_desc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occlusion',
            name='localized_desc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
