# Generated by Django 2.2.7 on 2019-12-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0002_auto_20191211_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalabnormal',
            name='oro_pharynx_desc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
