# Generated by Django 2.2.7 on 2019-12-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0003_auto_20191216_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occlusion',
            name='enamel',
        ),
        migrations.AddField(
            model_name='occlusion',
            name='abfraction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occlusion',
            name='abrasion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occlusion',
            name='attrition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occlusion',
            name='demineralization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occlusion',
            name='erosion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occlusion',
            name='fluorosis',
            field=models.BooleanField(default=False),
        ),
    ]
