# Generated by Django 2.2.7 on 2019-12-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0003_normalabnormal_oro_pharynx_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentalchart',
            old_name='is_approved',
            new_name='Ab',
        ),
        migrations.RemoveField(
            model_name='dentalchart',
            name='for_restoration',
        ),
        migrations.RemoveField(
            model_name='dentalchart',
            name='teeth_status',
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='Am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='CD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='CF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='Co',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='F',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='GC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='GI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='Imp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='In',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='M',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='MC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='P',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='PFG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='PFM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='PFS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='RC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='RPD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='SS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='Un',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='X',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='bottom',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='front',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='left',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='quadrant',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='right',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='top',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
