# Generated by Django 2.2.7 on 2019-12-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0004_auto_20191216_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occlusion',
            old_name='occlusion',
            new_name='occlusion_class',
        ),
    ]
