# Generated by Django 2.2.7 on 2019-12-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0005_auto_20191212_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalchart',
            name='APC',
            field=models.BooleanField(default=False),
        ),
    ]
