# Generated by Django 2.2.7 on 2019-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0005_auto_20191216_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gingiva',
            name='generalized',
        ),
        migrations.RemoveField(
            model_name='gingiva',
            name='horizontal',
        ),
        migrations.RemoveField(
            model_name='gingiva',
            name='localized',
        ),
        migrations.RemoveField(
            model_name='gingiva',
            name='none',
        ),
        migrations.RemoveField(
            model_name='gingiva',
            name='stage_1',
        ),
        migrations.RemoveField(
            model_name='gingiva',
            name='stage_2',
        ),
        migrations.RemoveField(
            model_name='gingiva',
            name='stage_3',
        ),
        migrations.RemoveField(
            model_name='gingiva',
            name='vertical',
        ),
        migrations.AddField(
            model_name='gingiva',
            name='radiographic_gl',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gingiva',
            name='radiographic_hv',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gingiva',
            name='radiographic_stage',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
