# Generated by Django 2.2.7 on 2019-12-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0006_dentalchart_apc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentalchart',
            old_name='front',
            new_name='middle',
        ),
    ]
