# Generated by Django 2.2.7 on 2019-12-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0007_auto_20191213_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackrecord',
            old_name='is_approved',
            new_name='is_approved_instructor',
        ),
        migrations.AddField(
            model_name='trackrecord',
            name='is_approved_patient',
            field=models.BooleanField(default=False),
        ),
    ]
