# Generated by Django 2.2.7 on 2019-12-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('track_record', '0008_treatmentrecord_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('procedure', models.CharField(max_length=100)),
                ('patient_signature', models.BooleanField(default=False)),
                ('clinical_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ClinicalInstructor')),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Clinician')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Patient')),
                ('track_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track_record.TrackRecord')),
            ],
        ),
    ]
