# Generated by Django 2.2.7 on 2019-12-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_record', '0009_cdar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdar',
            name='instructor_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='instructor_signature',
            field=models.BooleanField(default=False),
        ),
    ]
